---
AllCops:
  NewCops: enable
  Exclude:
    - Rakefile
    - Berksfile
    - Vagrantfile
    - Thorfile
    # - Gemfile
    - ".kitchen/*"
    - "vendor/**/*"
Chef/Modernize/FoodcriticComments:
  Enabled: true
Chef/Style/CopyrightCommentFormat:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# RSpec/IdenticalEqualityAssertion:
#   Enabled: true
# RSpec/Rails/AvoidSetupHook:
#   Enabled: true
